// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableHoverTranslate": boolean;
      "triggerMode": string;
      "modifierCtrl": boolean;
      "modifierAlt": boolean;
      "modifierShift": boolean;
      "enableHighlight": boolean;
      "highlightColor": string;
      "hoverDelay": number;
      "disableOnSelection": boolean;
      "popupAutoCloseDelay": number;
      "popupPosition": string;
      "translateDisplayMode": string;
      "translateEngine": string;
      "wordbookPlatform": string;
      "localSavePath": string;
      "enableEudicSync": boolean;
      "eudicToken": string;
      "eudicCategoryId": string;
      "eudicCategoryName": string;
      "maimemoToken": string;
      "maimemoCategoryId": string;
      "maimemoCategoryName": string;
      "shanbayToken": string;
      "shanbayCategoryId": string;
      "shanbayCategoryName": string;
      "eudicLanguage": string;
      "buttonShowScene": string;
      "wordButtonPosition": string;
      "addWordMode": string;
      "lemmaMode": string;
      "enableAnnotationSync": boolean;
      "enableAnnotationTranslate": boolean;
      "annotationTranslatePosition": string;
      "annotationTranslatePositionInBody": string;
      "annotationSeparatorMode": string;
      "annotationSeparator": string;
      "annotationWordPosition": string;
      "annotationMarkType": string;
      "annotationColor": string;
      "enableAnnotationAutoTag": boolean;
      "annotationTagName": string;
      "hideNoteIcon": boolean;
      "hideNoteIconMode": string;
      "hideNoteIconNotes": boolean;
      "annotationTrackedIDs": string;
      "exportAutoReveal": boolean;
      "exportSavePath": string;
    };
  }
}
