// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableHoverTranslate": boolean;
      "triggerMode": string;
      "modifierCtrl": boolean;
      "modifierAlt": boolean;
      "modifierShift": boolean;
      "enableHighlight": boolean;
      "highlightColor": string;
      "hoverDelay": number;
      "disableOnSelection": boolean;
      "enablePronunciationButton": boolean;
      "enableAutoPronunciation": boolean;
      "pronunciationShortcut": string;
      "popupAutoCloseDelay": number;
      "popupPosition": string;
      "translateDisplayMode": string;
      "translateEngine": string;
      "wordbookPlatform": string;
      "localSavePath": string;
      "enableEudicSync": boolean;
      "zoteroNoteTitle": string;
      "addWordShortcut": string;
      "eudicToken": string;
      "eudicCategoryId": string;
      "eudicCategoryName": string;
      "maimemoToken": string;
      "maimemoCategoryId": string;
      "maimemoCategoryName": string;
      "shanbayToken": string;
      "shanbayCategoryId": string;
      "shanbayCategoryName": string;
      "eudicLanguage": string;
      "buttonShowScene": string;
      "wordButtonPosition": string;
      "addWordMode": string;
      "lemmaMode": string;
      "syncToLocal": string;
      "enableTerminology": boolean;
      "terminologyPlatform": string;
      "terminologyLocalSavePath": string;
      "terminologyNoteTitle": string;
      "enableWordbookPanel": boolean;
      "panelFontSize": number;
      "panelHidePhon": boolean;
      "panelHideExp": boolean;
      "panelHidePlay": boolean;
      "panelHideAbbr": boolean;
      "panelWordScope": string;
      "panelSortMode": string;
      "panelContentMode": string;
      "enableAnnotationSync": boolean;
      "enableAnnotationTranslate": boolean;
      "annotationTranslatePosition": string;
      "annotationTranslatePositionInBody": string;
      "annotationSeparatorMode": string;
      "annotationSeparator": string;
      "annotationWordPosition": string;
      "annotationMarkType": string;
      "annotationColor": string;
      "enableAnnotationAutoTag": boolean;
      "annotationTagName": string;
      "enableTerminologyAnnotationSync": boolean;
      "terminologyMarkType": string;
      "terminologyColor": string;
      "terminologyTagName": string;
      "terminologyAnnotationTranslate": boolean;
      "terminologyTranslatePosition": string;
      "terminologyTranslatePositionInBody": string;
      "terminologySeparatorMode": string;
      "terminologySeparator": string;
      "terminologyWordPosition": string;
      "terminologyAnnotationAutoTag": boolean;
      "hideNoteIcon": boolean;
      "hideNoteIconMode": string;
      "hideNoteIconNotes": boolean;
      "annotationTrackedIDs": string;
      "exportContent": string;
      "exportAutoReveal": boolean;
      "exportSavePath": string;
      "prefActiveTab": string;
    };
  }
}
